### ISSUE TITLE
Allow to set watch paths

### ISSUE THREAD

**Issue by yesmeck** [SaitoWu/linner#42]
This is a feature request. In case you don't have time, I can send a PR.

**Comment by SaitoWu** [comment]
@yesmeck All of the `app`, `test`, `vendor` will be watched when linner are running.

So, do you need multiple paths in `app` key? I need more details.

:smile:

**Comment by yesmeck** [comment]
我想把 Linner 用到一个 [Phoenix](http://www.phoenixframework.org/) 的项目里，然后我想把目录组织成 `web/assets/scrtips`, `web/assets/styles` 这样去掉 `app` 目录。或者你有别的好的建议来组织目录结构吗？

**Comment by SaitoWu** [comment]
@yesmeck  

`app` 目录并不是必须的.

这里有一个例子: https://gist.github.com/SaitoWu/7715449

它的根目录是 `src`

同理, 你这个需求的话, 可以配置为:

```yaml
app: web/assets
```

这样 Linner 就只会 watch 这个目录.

同样的, 在 [saitowu/simba](https://github.com/SaitoWu/simba) 项目里也有这样的 [Linnerfile](https://github.com/SaitoWu/simba/blob/master/lib/simba/templates/Linnerfile), 它的配置是:

```yaml
app: "app/assets"
``` 

使用 bundle 的话, 默认会安装在 `ROOT/vendor` 目录下面, 同样可以配置这个目录, 默认为:

```yaml
vendor: vendor
```

**Comment by SaitoWu** [comment]
@yesmeck 因为 Phoenix 跟 Sinatra 很像, 所以我想你可以大部分配置都可以参考这个 [Linnerfile](https://github.com/SaitoWu/simba/blob/master/lib/simba/templates/Linnerfile).

Simba 也是为 Sinatra 量身定制的.

**Comment by yesmeck** [comment]
原来这些目录是可以配置的，那 OK 了，多谢。

**Comment by SaitoWu** [comment]
@yesmeck 更详细的配置文档在这里: https://github.com/SaitoWu/linner/blob/master/docs/config.md

**Comment by yesmeck** [comment]
:+1:
