### ISSUE TITLE
安装 bundle 时的 vendor 路径不是从配置文件里读取的？

### ISSUE THREAD

**Issue by yesmeck** [SaitoWu/linner#43]
https://github.com/SaitoWu/linner/blob/master/lib%2Flinner%2Fbundler.rb#L8

**Comment by SaitoWu** [comment]
哦, 这里不是从配置文件读取的 

这里的 bundle 有问题, 应该从配置文件读取.

**Comment by SaitoWu** [comment]
@yesmeck 已推送最新源码, 修复了这个问题.

可以 clone 源码后, 手动在目录下 `rake install` 安装.

待我运行测试无误后会 release 正式版在 Rubygems 上.

:bow: :bow: :bow:

**Comment by yesmeck** [comment]
:100:
