### ISSUE TITLE
Asset.rb File.open mode

### ISSUE THREAD

**Issue by jackeyvzhang** [SaitoWu/linner#45]
asset.rb第44行
File.read(path, mode: "rb")
这里读取文件的模式为何是rb而不使用rt? 当拼接文件中包含中文的时候，这里就挂了

**Comment by SaitoWu** [comment]
拼接文件如果是可识别的后缀, 会以上面的方式, 会用 Tilt 去渲染的.

你这个文件可能是不可识别的文件后缀.

不可识别的后缀默认是以二进制文件处理的, 这是默认行为. 同时用 "rb", 是为了保证 Windows 的处理文件行为正确.
