### ISSUE TITLE
linner安装

### ISSUE THREAD

**Issue by 0532** [SaitoWu/linner#46]
我使用命令```gem install linner```   安装总的出错，我是否可以下载一个release，然后使用吗，win7系统

**Comment by anson0370** [comment]
http://pan.baidu.com/s/1dDjehzz 这里的压缩包可以傻瓜安装 但如果你自己要使用ruby和node环境 这种安装方式并不合适（因为实际上打包了一个ruby和node）

所以还是麻烦把错误发上来看看

**Comment by 0532** [comment]
谢谢了 ，我的可能是ruby的版本有点低。
