### ISSUE TITLE
do we have  full document for linner  in  Chinese 

### ISSUE THREAD

**Issue by mullerhai** [SaitoWu/linner#51]
大神，我们公司用这个linner ，没有文档，开发速度老慢了

**Comment by anson0370** [comment]
哥们你是哪个公司的？

**Comment by SaitoWu** [comment]
@mullerhai 这里有一篇文章，可以参考理念和配置 https://ruby-china.org/topics/25802

**Comment by mullerhai** [comment]
@anson0370  Gome 国美

**Comment by mullerhai** [comment]
@SaitoWu 谢谢了 大神

**Comment by mullerhai** [comment]
@SaitoWu  大神 加个微信吧， mullerhelen，这个和java  前后端分离还是很棒的一个架构，

**Comment by anson0370** [comment]
@mullerhai 我们现在在做一个基于 node 的更彻底的前后端分离 更棒 😄

**Comment by mullerhai** [comment]
@anson0370  太棒了，大师，求加微信：mullerhelen   ，大师  ，这个基于node 的是否可以帮助我们公司做二次重构吗，可是我没有抉择权利，这个基于node的可以分享出来吗

**Comment by mullerhai** [comment]
@anson0370 这个基于node 的可以开源吗 ，

**Comment by anson0370** [comment]
@mullerhai 有机会的话可以给你们升级啊 不过不是你我能决定的
